Feature/functions construction
mvrsdev/car-specs pull request #6
Opened 2022-04-29 16:19 UTC by mvrsdev

Created 4 new functions for this project: 

1. One for the total valves count;
2. One for check the capacity of each cylinder;
3. One for check the weight/power ratio of the car;
4. And one for measure the maximum torque of each gear.  

And I also refactored the fordFocus object.

2022-04-29 22:02 UTC, thi-days requested changes

2022-04-29 22:10 UTC, mvrsdev commented on scripts/car.js
> +  return `${car.engine.cylinderTotalCapacity / car.engine.cylinderCount}`;
I sincerely don't know why I did that.

2022-04-29 22:11 UTC, mvrsdev commented on scripts/car.js
> +  return `${car.engine.cylinderCount * car.engine.cylinderValveCount}V`;
Corrected.

2022-04-29 22:11 UTC, mvrsdev commented on scripts/car.js
> +  return `${carWeightPowerRatio.toFixed(2)} kg/cv`;
Also corrected

2022-04-30 00:41 UTC, thi-days approved these changes

2022-04-30 00:41 UTC, merged